; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_deps = 
    bolderflight/Bolder Flight Systems SBUS@^8.1.4
    bblanchon/ArduinoJson @ ^7.0.0
build_flags =
    ;-D SBUS_DRIVER=1   ; 1 = bolderflight (Published library, SBUS-16)
    ;-D SBUS_DRIVER=2   ; 2 = sbus16_native
    -D SBUS_DRIVER=3   ; 3 = sbus24_native
    ;-D SBUS_DRIVER=4   ; 4 = bolderflight with SBUS-24 modifications (see src/sbus24_bolderflight.h/cpp)
    -D SBUS_SERIAL=Serial5  ; Pin 21 on Teensy 4.1, change if using different board or driver

    ; CAN BUS Settings
    -D CAN_ENABLED=1
    -D CAN_STARTUP_SCANNER=1
    -D CAN_STARTUP_SCANNER_TIMEOUT_MS=15000
    -D CAN_TX_PIN=22
    -D CAN_RX_PIN=23
    -D CAN_BAUD_RATE=500000
    -D CAN_FRAME_GAP_MS=1
    -D CAN_USE_EXTENDED_ID=0
    -D CAN_USE_LOOPBACK=0
    -D CAN_USE_LOOPBACK_MODE=0
    -D CAN_USE_SILENT_MODE=0
    -D CAN_USE_FD_MODE=0
    -D CAN_USE_ONE_SHOT_MODE=0
    -D CAN_USE_ERROR_COUNTERS=0
    -D CAN_USE_BUS_MONITOR_MODE=0
    -D CAN_USE_WAKEUP_FILTER=0
    -D CAN_USE_AUTO_RETRANSMISSION=1
    -D CAN_USE_TX_QUEUE=1
    -D CAN_USE_RX_QUEUE=1
    -D CAN_USE_FILTER_QUEUE=1
    -D CAN_USE_TIMESTAMP=0
    -D CAN_USE_BUS_LOAD_MONITOR=0
    -D CAN_USE_ERROR_INTERRUPT=0
    -D CAN_USE_BUS_OFF_RECOVERY=1
    -D CAN_USE_SLEEP_MODE=0
    -D CAN_USE_WAKEUP_MODE=0
    -D CAN_USE_SELF_TEST_MODE=0
