; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
upload_port = COM6
monitor_port = COM6
platform = teensy
board = teensy41
framework = arduino
lib_deps =
	bolderflight/Bolder Flight Systems SBUS@^8.1.4
	adafruit/Adafruit NeoPixel@^1.15.4
	dfrobot/DFRobotDFPlayerMini@^1.0.6
	makuna/NeoPixelBus@^2.8.4
	;pololu/PololuMaestro@^1.0.0
	bblanchon/ArduinoJson@^7.4.3
	PowerBroker2/SerialTransfer@^3.1.2

build_flags = 
	-D SBUS_DRIVER=3
	
	-D DF_SERIAL=Serial2
	-D SBUS_SERIAL=Serial8
	
	-D MAPPING_DEBUG=0
	
	-D WATCHDOG_ENABLED=0
	-D WATCHDOG_TIMEOUT_SECONDS=10
	
	-D WAIT_FOR_SERIAL=0
	-D HEARTBEAT_INTERVAL_MS=5000
	-D PRINT_ALL_INTERVAL_MS=30000
	-D DEBUG_SCOMP_RX=1
	-D SCOMP_BAUD_RATE=460800
	-D SCOMP_SEND_INTERVAL_MS=50
    -D SCOMP_FLAG_NODE_LOCAL=1
    -D SCOMP_FLAG_NODE_REMOTE=2
